### ISSUE TITLE
Programming language is wrong

### ISSUE THREAD

**Issue by Revokeez** [makbro/HelloGitHub#1]
;This should be the code

section .data
    hello db 'Hello, World!',0  ; Null-terminated string

section .text
global _start

_start:
    ; Write "Hello, World!" to stdout
    mov eax, 4                  ; syscall number for sys_write
    mov ebx, 1                  ; file descriptor 1 (stdout)
    mov ecx, hello              ; pointer to the string to print
    mov edx, 13                 ; length of the string
    int 0x80                    ; interrupt to invoke the syscall

    ; Exit the program
    mov eax, 1                  ; syscall number for sys_exit
    mov ebx, 0                  ; return code 0
    int 0x80                    ; interrupt to invoke the syscall

**Comment by hbruckman** [comment]
Thanks for reporting this.
